version: '3.4'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accesscontrol
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  accesscontrol:
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}accesscontrol
    build:
      context: .
      dockerfile: AccessControl/Dockerfile
    ports:
      - "8080:80"

volumes:
   dbdata: