using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;

namespace AccessControl.Messages
{
    /// <summary>
    /// A representation of the error that occurs in an api operation
    /// </summary>
    public class ApiErrorResponse
    {
        /// <summary>
        /// Error code generated by the problem
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// Human readable explanation of the error condition
        /// </summary>
        public string Detail { get; set; }
        /// <summary>
        /// Human readable summary
        /// </summary>
        public string Title { get; set; }
    }
}
